name: Cypress(Development Build)
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress/configs/ci-build.json
          start: DISABLE_ESLINT_PLUGIN=true yarn start
          wait-on: 'http://localhost:3000'
          browser: chrome

      - name: Cypress Upload Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Cypress Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports
          retention-days: 7