name: Cypress tests against development build
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress/configs/ci-build.json
          start: yarn start
          wait-on: 'http://localhost:3000'
          browser: chrome